# Generated by Django 3.1.4 on 2020-12-17 20:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userproperties',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userproperties',
            name='password_restore_called',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 17, 20, 30, 38, 732183, tzinfo=utc)),
        ),
    ]
