# Generated by Django 3.1.4 on 2020-12-17 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201217_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproperties',
            name='password_restore_called',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
