# Generated by Django 3.1.4 on 2020-12-20 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201218_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='email_key',
        ),
        migrations.AddField(
            model_name='userproperties',
            name='email_confirm_called',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='email_key_restoration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='email_key_verification',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userproperties',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
