# Generated by Django 3.1.4 on 2020-12-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201220_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
