# Generated by Django 3.1.4 on 2021-01-07 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userproperties_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproperties',
            name='rating',
        ),
    ]
