# Generated by Django 3.1.4 on 2021-01-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userproperties_rating'),
        ('accounts', '0006_complaint'),
    ]

    operations = [
    ]
