# Generated by Django 3.1.4 on 2021-01-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210110_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproperties',
            name='permanent_ban',
            field=models.BooleanField(default=False),
        ),
    ]
