# Generated by Django 3.1.4 on 2021-01-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_survey_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='survey',
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='text',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=255)),
                ('survey', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surveys.survey')),
            ],
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='surveyQuestion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion'),
        ),
    ]
