# Generated by Django 3.1.4 on 2021-01-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20210102_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='multipleChoice',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='multipleChoice',
            field=models.BooleanField(default=False),
        ),
    ]
