# Generated by Django 3.1.4 on 2021-01-03 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_auto_20210102_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='survey',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
