# Generated by Django 3.1.4 on 2021-01-07 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surveys', '0006_auto_20210103_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='downed',
            field=models.ManyToManyField(related_name='downed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='upped',
            field=models.ManyToManyField(related_name='upped', to=settings.AUTH_USER_MODEL),
        ),
    ]
