# Generated by Django 3.1.4 on 2021-01-14 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20210114_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='creationTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
