# Generated by Django 3.1.4 on 2021-01-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0010_commentary_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
